Navbar fixed + shadow
ntkme/github-buttons-app pull request #2
Opened 2020-09-08 00:27 UTC by techboyg5

Adds a shadow and fixed positioning to the navbar.

2020-09-08 00:35 UTC, ntkme commented on public/index.html
> +    <header class="header user-select-none shadow fixed-top bg-white">
Use sticky-top so that there is no need to hard code `padding-top` on `.main`

2020-09-08 00:37 UTC, ntkme requested changes

2020-09-08 00:37 UTC, ntkme commented on public/index.html
> +    <header class="header user-select-none shadow fixed-top bg-white">
Use sticky-top so that there is no need to hard code `padding-top` on `.main`

2020-09-08 00:37 UTC, ntkme commented on public/index.html
> +    <main class="main" style="padding-top:57px">
Use `sticky-top` on `header` and remove this padding.

2020-09-08 00:37 UTC, ntkme commented on public/index.html
> +    <header class="header user-select-none shadow fixed-top bg-white">
It's opinionated to not have shadow to be consistent with GitHub sites.

2020-09-08 00:38 UTC, techboyg5 commented on public/index.html
> +    <header class="header user-select-none shadow fixed-top bg-white">
It doesn't work on IE11. fixed-top + padding-top works just as fine

2020-09-08 00:38 UTC, techboyg5 commented on public/index.html
> +    <main class="main" style="padding-top:57px">
It doesn't work on IE11. fixed-top + padding-top works just as fine

2020-09-08 00:38 UTC, techboyg5 commented on public/index.html
> +    <header class="header user-select-none shadow fixed-top bg-white">
OK. I'll remove the shadow,

2020-09-08 00:50 UTC, ntkme commented on public/index.html
> +    <main class="main" style="padding-top:57px">
Yes, it "doesn't work" on IE 11, but it also does not break any functionality (thus a progressive enhancement).

The "buttons.js" script does target all browsers including super old browsers like IE 6 / Firefox 4 etc, because it's designed to be put on other sites thus it's better to have max compatibility. However, there is no need to support IE 11 for the button generator site as GitHub already dropped IE 11 support back in 2018.

2020-09-08 01:00 UTC, techboyg5 commented on public/index.html
> +    <main class="main" style="padding-top:57px">
The website "github.com" has nothing to do with these buttons except that they are links to pages on the github.com website.

2020-09-08 01:23 UTC, ntkme commented on public/index.html
> +    <main class="main" style="padding-top:57px">
There is no affiliation or anything but this is targeting the same user base as GitHub.com, thus wouldn’t it make sense to target the supported browser in a similar way?

2020-09-08 16:39 UTC, techboyg5 commented on public/index.html
> +    <main class="main" style="padding-top:57px">
What's wrong with how it is right now? Please tell me.

2020-10-07 00:06 UTC, techboyg5 commented
Sticky top is done!

2021-01-10 12:13 UTC, closed without merging